import React, { useEffect, useState } from 'react';
import { Lead } from '../types';

interface LeadDetailModalProps {
  lead: Lead;
  onClose: () => void;
  onSave: (result: string, notes: string) => void;
  focusCallResult?: boolean;
}

const CALL_RESULTS = [
  'No Answer',
  'Call Back',
  'Not Interested',
  'Booked'
] as const;

const LeadDetailModal: React.FC<LeadDetailModalProps> = ({
  lead,
  onClose,
  onSave,
  focusCallResult
}) => {
  const [result, setResult] = useState('');
  const [newNote, setNewNote] = useState('');
  const [error, setError] = useState<string | null>(null);

  // Auto-focus call result when opened from phone icon
  useEffect(() => {
    if (focusCallResult) {
      const el = document.getElementById('call-result-select');
      el?.focus();
    }
  }, [focusCallResult]);

  const handleLogResult = () => {
    if (!result) {
      setError('Please select a call result');
      return;
    }

    setError(null);
    onSave(result, newNote.trim());
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/70 backdrop-blur-sm">
      <div className="bg-[#0a0f1d] w-full sm:max-w-[600px] max-h-[90vh] overflow-y-auto rounded-t-3xl sm:rounded-2xl border-t border-slate-800 flex flex-col p-6 animate-in slide-in-from-bottom duration-300">

        {/* Header */}
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-bold text-white truncate">
            {lead.name}
          </h2>
          <button
            onClick={onClose}
            className="text-slate-400 p-2 hover:bg-slate-800 rounded-full transition-colors"
            aria-label="Close"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Lead Information */}
        <section className="space-y-4 mb-8">
          <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
            Lead Information
          </h3>
          <div className="space-y-3">
            <div>
              <p className="text-xs text-slate-500">Name</p>
              <p className="font-medium text-white">{lead.name}</p>
            </div>
            <div>
              <p className="text-xs text-slate-500">Address</p>
              <p className="font-medium text-white truncate">{lead.address}</p>
            </div>
            <div>
              <p className="text-xs text-slate-500">Contact Number</p>
              <p className="font-medium text-blue-400">{lead.phone}</p>
            </div>
          </div>
        </section>

        {/* Qualification */}
        <section className="space-y-4 mb-8">
          <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
            Qualification
          </h3>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-xs text-slate-500">Renter / Owner</p>
              <p className="font-medium text-white">{lead.renterOwner || '—'}</p>
            </div>
            <div>
              <p className="text-xs text-slate-500">Superannuation</p>
              <p className="font-medium text-white">{lead.superannuation || '—'}</p>
            </div>
            <div>
              <p className="text-xs text-slate-500">Employment</p>
              <p className="font-medium text-white">{lead.employmentType || '—'}</p>
            </div>
          </div>
        </section>

        {/* History */}
        <section className="space-y-4 mb-8">
          <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
            Lead History
          </h3>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-xs text-slate-500">Generated By</p>
              <p className="font-medium text-white">{lead.generatedBy || '—'}</p>
            </div>
            <div>
              <p className="text-xs text-slate-500">Status</p>
              <p className="font-medium text-white">{lead.status}</p>
            </div>
            <div>
              <p className="text-xs text-slate-500">Last Contacted By</p>
              <p className="font-medium text-white">{lead.lastContactedBy || '—'}</p>
            </div>
            <div>
              <p className="text-xs text-slate-500">Last Contact Date</p>
              <p className="font-medium text-white text-sm">
                {lead.lastContactDate || '—'}
              </p>
            </div>
          </div>
        </section>

        {/* Notes History */}
        <section className="space-y-4 mb-8">
          <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
            Notes History
          </h3>
          <div className="bg-slate-900/50 rounded-xl p-3 max-h-40 overflow-y-auto border border-slate-800">
            {lead.notes.length > 0 ? (
              lead.notes.map((note, idx) => (
                <div
                  key={idx}
                  className="mb-3 last:mb-0 pb-3 last:pb-0 border-b border-slate-800 last:border-0 text-sm text-slate-300"
                >
                  {note}
                </div>
              ))
            ) : (
              <p className="text-sm text-slate-500 italic">No historical notes</p>
            )}
          </div>
        </section>

        {/* Call Result */}
        <section
          className={`space-y-4 p-4 bg-slate-900 rounded-2xl border ${
            focusCallResult
              ? 'border-blue-500/50 ring-2 ring-blue-500/20'
              : 'border-slate-800'
          }`}
        >
          <h3 className="text-sm font-semibold text-white">Log Call Result</h3>

          <div>
            <label className="block text-xs text-slate-400 mb-1">
              Select Result
            </label>
            <select
              id="call-result-select"
              value={result}
              onChange={(e) => setResult(e.target.value)}
              className="w-full bg-[#0a0f1d] border border-slate-700 rounded-lg p-3 text-sm focus:ring-2 focus:ring-blue-500 outline-none"
            >
              <option value="">Choose a result…</option>
              {CALL_RESULTS.map((r) => (
                <option key={r} value={r}>
                  {r}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs text-slate-400 mb-1">
              Add Note
            </label>
            <textarea
              value={newNote}
              onChange={(e) => setNewNote(e.target.value)}
              placeholder="Enter new note details…"
              className="w-full bg-[#0a0f1d] border border-slate-700 rounded-lg p-3 text-sm min-h-[100px] focus:ring-2 focus:ring-blue-500 outline-none"
            />
          </div>

          {error && (
            <p className="text-sm text-red-400 font-medium">{error}</p>
          )}

          <button
            onClick={handleLogResult}
            disabled={!result}
            className="w-full bg-[#d4af37] hover:bg-[#c4a030] disabled:opacity-50 disabled:cursor-not-allowed text-[#0a0f1d] font-bold py-4 rounded-xl transition-transform active:scale-95 shadow-lg"
          >
            Log Result
          </button>
        </section>
      </div>
    </div>
  );
};

export default LeadDetailModal;
